version: 2.1

orbs:
  android: circleci/android@2.1.1

executors:
  android-executor:
    docker:
      - image: circleci/android:2022.04.1
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx4096m -Dkotlin.compiler.execution.strategy=in-process'
      ANDROID_HOME: /opt/android/sdk
      ANDROID_SDK_ROOT: /opt/android/sdk
      JAVA_HOME: /usr/local/openjdk-11

jobs:
  unit_tests:
    executor: android-executor
    steps:
      - checkout

      - android/gradle-cache@2:
          path: ~/.gradle/caches

      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest

      - android/gradle-cache@2:
          path: ~/.gradle/caches
          write: true

  ui_tests:
    executor: android-executor
    steps:
      - checkout

      - android/gradle-cache@2:
          path: ~/.gradle/caches

      - android/setup:
          api-level: 30
          target: default
          build-tools: "30.0.3"

      - run:
          name: Run UI Tests
          command: ./gradlew connectedAndroidTest

      - android/gradle-cache@2:
          path: ~/.gradle/caches
          write: true

  build:
    executor: android-executor
    steps:
      - checkout

      - android/gradle-cache@2:
          path: ~/.gradle/caches

      - run:
          name: Build Application
          command: ./gradlew assembleDebug

      - android/gradle-cache@2:
          path: ~/.gradle/caches
          write: true

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
      - ui_tests:
          requires:
            - unit_tests
      - build:
          requires:
            - unit_tests